lidiannerb/SAP007-burger-queen-api-client

package-lock.json
package.json
src/App.js
src/routes.jsx

feat: install routes

---

src/pages/login/index.jsx
src/pages/login/style.css
src/pages/register/index.jsx
src/services/data.js

feat: create user

---

src/pages/login/index.jsx
src/pages/register/index.jsx

feat: redirect register and login

---

.eslintrc.json
package-lock.json
package.json
src/pages/login/index.jsx
src/pages/register/index.jsx
src/routes.jsx

style: eslint config

---

src/pages/register/index.jsx
src/services/errors/error.js

feat: save token no console

---

src/components/header/index.jsx
src/pages/login/index.jsx
src/pages/login/style.css
src/pages/menu/index.jsx
src/pages/register/index.jsx
src/routes.jsx
src/services/data.js
src/services/token/index.js

feat: get product

---

src/pages/menu/index.jsx
src/pages/menu/style.css
src/services/data/index.js

feat: get product menu

---

src/components/SelectTable/index.jsx
src/components/buttonInsertProducts/index.jsx
src/components/card/index.jsx
src/pages/menu/index.jsx

feat: adjustments menu and filter

---

src/components/buttonInsertProducts/index.jsx
src/components/comand/index.jsx
src/pages/menu/index.jsx

feat: adc products on command

---

src/components/button/index.jsx
src/components/comand/index.jsx
src/pages/login/index.jsx
src/pages/menu/index.jsx
src/pages/register/index.jsx

feat: add and remove quantity of products

---

package-lock.json
package.json
src/components/header/index.jsx
src/components/header/style.css
src/components/layout/index.jsx
src/components/layout/style.css
src/pages/login/index.jsx
src/pages/login/style.css
src/pages/menu/index.jsx
src/pages/menu/style.css
src/pages/register/style.css

feat: adding logout icon and some header tweaks

---

src/components/SelectTable/index.jsx
src/components/inputs/index.jsx
src/pages/login/index.jsx
src/pages/menu/index.jsx
src/pages/register/index.jsx

feat: WIP / add table and client at command

---

src/components/comand/index.jsx
src/pages/menu/index.jsx
src/services/data/index.js

feat: add table-client at command and create order

---

src/components/header/index.jsx
src/pages/menu/index.jsx
src/services/token/index.js

feat: logout menu

---

src/components/button/style.css
src/components/header/index.jsx
src/components/header/style.css
src/pages/login/index.jsx
src/pages/menu/index.jsx
src/pages/menu/style.css
src/pages/register/index.jsx

feat: WIP/ style-menu

---

src/components/SelectTable/index.jsx
src/components/SelectTable/styles.css
src/components/button/style.css
src/components/card/index.jsx
src/components/card/style.css
src/components/comand/index.jsx
src/components/comand/style.css
src/components/inputs/style.css
src/pages/login/index.jsx
src/pages/menu/index.jsx
src/pages/menu/style.css
src/pages/register/index.jsx
src/style/global.css

feat: adding style to the page menu and components

---

src/components/errorMessages/index.jsx
src/pages/login/index.jsx
src/pages/menu/index.jsx
src/pages/menu/style.css
src/pages/register/index.jsx
src/services/errors/index.js

feat: component errors - adjustments

---

src/components/comand/index.jsx
src/pages/menu/index.jsx
src/services/handleLogout/index.js

feat: WIP feat- remove order sent

---

src/components/SelectTable/index.jsx
src/components/comand/index.jsx
src/components/header/index.jsx
src/pages/kitchen/index.jsx
src/pages/login/index.jsx
src/pages/menu/index.jsx
src/routes.jsx
src/services/handleLogout/index.js

feat: WIP feat-kitchen-page-in-progress

---

src/components/button/style.css
src/components/header/index.jsx
src/components/header/style.css
src/components/navbar/index.jsx
src/components/navbar/style.css

feat: WIP - menu hamburguer

---

src/routes.jsx

feat: add private route

---

src/components/navbar/style.css

feat: fix-logout

---

src/components/layout/style.css
src/pages/login/index.jsx
src/pages/register/index.jsx

fix: adding routes on register page

---

src/components/button/test.js
src/test/App.test.js

test: testing component Button

---

src/components/cardOrder/index.jsx
src/components/cardOrder/style.css
src/pages/kitchen/index.jsx
src/pages/kitchen/style.css
src/pages/menu/index.jsx
src/services/data/index.js

feat: WIP - add page kitchen

---

src/pages/menu/index.jsx

feat: filters button changes color when selected

---

src/components/card/index.jsx
src/components/cardOrder/index.jsx
src/pages/kitchen/index.jsx

feat: WIP - add feature cardOrder

---

package-lock.json
package.json
src/components/cardOrder/index.jsx
src/components/cardOrder/style.css
src/pages/kitchen/index.jsx
src/pages/kitchen/style.css
src/services/data/index.js
src/services/dateOrder/index.js

feat: ordering orders in the kitchen

---

src/components/cardOrder/index.jsx
src/pages/kitchen/index.jsx
src/services/data/index.js

feat: WIP update status

---

src/pages/kitchen/index.jsx
src/services/data/index.js

feat: WIP add status in orders

---

src/pages/kitchen/index.jsx

feat:  update status

---

src/pages/readyOrders/index.jsx

feat: serve orders done

---

src/pages/readyOrders/index.jsx

feat: WIP sorted orders

---

src/components/cardOrder/index.jsx
src/pages/kitchen/index.jsx
src/pages/login/index.jsx
src/pages/menu/index.jsx
src/pages/readyOrders/index.jsx
src/pages/register/index.jsx

feat: ordering and add button on orders done

---

src/pages/kitchen/index.jsx

fix: orders served

---

src/components/button/style.css
src/components/card/index.jsx
src/components/cardOrder/index.jsx
src/components/cardOrder/style.css
src/pages/kitchen/index.jsx
src/pages/kitchen/style.css

feat: WIP style pages

---

src/components/card/index.jsx
src/components/cardOrder/index.jsx
src/components/cardOrder/style.css
src/pages/kitchen/index.jsx
src/pages/kitchen/style.css
src/services/dateOrder/index.js

feat:  wip style page

---

src/components/cardOrder/index.jsx
src/components/cardOrder/style.css
src/components/navbar/index.jsx
src/components/navbar/style.css
src/pages/historic/index.jsx
src/pages/historic/style.css
src/pages/kitchen/index.jsx
src/pages/kitchen/style.css
src/routes.jsx

feat: wip status buttons

---

src/components/cardOrder/index.jsx

fix: preparationTime
